sudo: 'required'

language: go
go:
- "1.11"

services:
  - 'docker'

before_install:
  - './.travis/main.sh'
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
  - dep ensure

script:
  - 'make test image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi

notifications:
  email: false
