// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/user/proto/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserInfoRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{0}
}
func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(dst, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsAdmin              bool     `protobuf:"varint,3,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{1}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type CreateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{2}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserRequest struct {
	UserToken            string   `protobuf:"bytes,1,opt,name=userToken,proto3" json:"userToken,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{3}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *UpdateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{4}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(dst, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type DeleteUserRequest struct {
	UserToken            string   `protobuf:"bytes,1,opt,name=userToken,proto3" json:"userToken,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{5}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *DeleteUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{6}
}
func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(dst, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type GetTokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{7}
}
func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(dst, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetTokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetAccessTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenResponse) Reset()         { *m = GetAccessTokenResponse{} }
func (m *GetAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenResponse) ProtoMessage()    {}
func (*GetAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{8}
}
func (m *GetAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenResponse.Unmarshal(m, b)
}
func (m *GetAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenResponse.Merge(dst, src)
}
func (m *GetAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenResponse.Size(m)
}
func (m *GetAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenResponse proto.InternalMessageInfo

func (m *GetAccessTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetAccessTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetUserByAccessTokenRequest struct {
	UserToken            string   `protobuf:"bytes,1,opt,name=userToken,proto3" json:"userToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByAccessTokenRequest) Reset()         { *m = GetUserByAccessTokenRequest{} }
func (m *GetUserByAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccessTokenRequest) ProtoMessage()    {}
func (*GetUserByAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{9}
}
func (m *GetUserByAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccessTokenRequest.Unmarshal(m, b)
}
func (m *GetUserByAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccessTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserByAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccessTokenRequest.Merge(dst, src)
}
func (m *GetUserByAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccessTokenRequest.Size(m)
}
func (m *GetUserByAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccessTokenRequest proto.InternalMessageInfo

func (m *GetUserByAccessTokenRequest) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

type GetUserByAccessTokenResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByAccessTokenResponse) Reset()         { *m = GetUserByAccessTokenResponse{} }
func (m *GetUserByAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByAccessTokenResponse) ProtoMessage()    {}
func (*GetUserByAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{10}
}
func (m *GetUserByAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByAccessTokenResponse.Unmarshal(m, b)
}
func (m *GetUserByAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByAccessTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserByAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByAccessTokenResponse.Merge(dst, src)
}
func (m *GetUserByAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByAccessTokenResponse.Size(m)
}
func (m *GetUserByAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByAccessTokenResponse proto.InternalMessageInfo

func (m *GetUserByAccessTokenResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetRefreshTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRefreshTokenResponse) Reset()         { *m = GetRefreshTokenResponse{} }
func (m *GetRefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetRefreshTokenResponse) ProtoMessage()    {}
func (*GetRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{11}
}
func (m *GetRefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRefreshTokenResponse.Unmarshal(m, b)
}
func (m *GetRefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRefreshTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GetRefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRefreshTokenResponse.Merge(dst, src)
}
func (m *GetRefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetRefreshTokenResponse.Size(m)
}
func (m *GetRefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRefreshTokenResponse proto.InternalMessageInfo

func (m *GetRefreshTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshAccessTokenRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenRequest) Reset()         { *m = RefreshAccessTokenRequest{} }
func (m *RefreshAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenRequest) ProtoMessage()    {}
func (*RefreshAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{12}
}
func (m *RefreshAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenRequest.Unmarshal(m, b)
}
func (m *RefreshAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenRequest.Marshal(b, m, deterministic)
}
func (dst *RefreshAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenRequest.Merge(dst, src)
}
func (m *RefreshAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenRequest.Size(m)
}
func (m *RefreshAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenRequest proto.InternalMessageInfo

func (m *RefreshAccessTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshAccessTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshAccessTokenResponse) Reset()         { *m = RefreshAccessTokenResponse{} }
func (m *RefreshAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshAccessTokenResponse) ProtoMessage()    {}
func (*RefreshAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{13}
}
func (m *RefreshAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshAccessTokenResponse.Unmarshal(m, b)
}
func (m *RefreshAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshAccessTokenResponse.Marshal(b, m, deterministic)
}
func (dst *RefreshAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshAccessTokenResponse.Merge(dst, src)
}
func (m *RefreshAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshAccessTokenResponse.Size(m)
}
func (m *RefreshAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshAccessTokenResponse proto.InternalMessageInfo

func (m *RefreshAccessTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshAccessTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type CreateAppRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{14}
}
func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(dst, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateAppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateAppResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppResponse) Reset()         { *m = CreateAppResponse{} }
func (m *CreateAppResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAppResponse) ProtoMessage()    {}
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{15}
}
func (m *CreateAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppResponse.Unmarshal(m, b)
}
func (m *CreateAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppResponse.Merge(dst, src)
}
func (m *CreateAppResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAppResponse.Size(m)
}
func (m *CreateAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppResponse proto.InternalMessageInfo

func (m *CreateAppResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAppResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type GetAppInfoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppInfoRequest) Reset()         { *m = GetAppInfoRequest{} }
func (m *GetAppInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppInfoRequest) ProtoMessage()    {}
func (*GetAppInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{16}
}
func (m *GetAppInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppInfoRequest.Unmarshal(m, b)
}
func (m *GetAppInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetAppInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppInfoRequest.Merge(dst, src)
}
func (m *GetAppInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppInfoRequest.Size(m)
}
func (m *GetAppInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppInfoRequest proto.InternalMessageInfo

func (m *GetAppInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAppInfoResponse struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppInfoResponse) Reset()         { *m = GetAppInfoResponse{} }
func (m *GetAppInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppInfoResponse) ProtoMessage()    {}
func (*GetAppInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{17}
}
func (m *GetAppInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppInfoResponse.Unmarshal(m, b)
}
func (m *GetAppInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppInfoResponse.Marshal(b, m, deterministic)
}
func (dst *GetAppInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppInfoResponse.Merge(dst, src)
}
func (m *GetAppInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppInfoResponse.Size(m)
}
func (m *GetAppInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppInfoResponse proto.InternalMessageInfo

func (m *GetAppInfoResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GetAppInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetOAuthCodeRequest struct {
	AppUid               string   `protobuf:"bytes,1,opt,name=appUid,proto3" json:"appUid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOAuthCodeRequest) Reset()         { *m = GetOAuthCodeRequest{} }
func (m *GetOAuthCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetOAuthCodeRequest) ProtoMessage()    {}
func (*GetOAuthCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{18}
}
func (m *GetOAuthCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOAuthCodeRequest.Unmarshal(m, b)
}
func (m *GetOAuthCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOAuthCodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetOAuthCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOAuthCodeRequest.Merge(dst, src)
}
func (m *GetOAuthCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetOAuthCodeRequest.Size(m)
}
func (m *GetOAuthCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOAuthCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOAuthCodeRequest proto.InternalMessageInfo

func (m *GetOAuthCodeRequest) GetAppUid() string {
	if m != nil {
		return m.AppUid
	}
	return ""
}

func (m *GetOAuthCodeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetOAuthCodeRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetOAuthCodeResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOAuthCodeResponse) Reset()         { *m = GetOAuthCodeResponse{} }
func (m *GetOAuthCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetOAuthCodeResponse) ProtoMessage()    {}
func (*GetOAuthCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{19}
}
func (m *GetOAuthCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOAuthCodeResponse.Unmarshal(m, b)
}
func (m *GetOAuthCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOAuthCodeResponse.Marshal(b, m, deterministic)
}
func (dst *GetOAuthCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOAuthCodeResponse.Merge(dst, src)
}
func (m *GetOAuthCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetOAuthCodeResponse.Size(m)
}
func (m *GetOAuthCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOAuthCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOAuthCodeResponse proto.InternalMessageInfo

func (m *GetOAuthCodeResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type GetTokenFromCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	AppUid               string   `protobuf:"bytes,2,opt,name=appUid,proto3" json:"appUid,omitempty"`
	AppSecret            string   `protobuf:"bytes,3,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenFromCodeRequest) Reset()         { *m = GetTokenFromCodeRequest{} }
func (m *GetTokenFromCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenFromCodeRequest) ProtoMessage()    {}
func (*GetTokenFromCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{20}
}
func (m *GetTokenFromCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenFromCodeRequest.Unmarshal(m, b)
}
func (m *GetTokenFromCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenFromCodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokenFromCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenFromCodeRequest.Merge(dst, src)
}
func (m *GetTokenFromCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenFromCodeRequest.Size(m)
}
func (m *GetTokenFromCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenFromCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenFromCodeRequest proto.InternalMessageInfo

func (m *GetTokenFromCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetTokenFromCodeRequest) GetAppUid() string {
	if m != nil {
		return m.AppUid
	}
	return ""
}

func (m *GetTokenFromCodeRequest) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type GetTokenFromCodeResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenFromCodeResponse) Reset()         { *m = GetTokenFromCodeResponse{} }
func (m *GetTokenFromCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenFromCodeResponse) ProtoMessage()    {}
func (*GetTokenFromCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_d91e02009efc5113, []int{21}
}
func (m *GetTokenFromCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenFromCodeResponse.Unmarshal(m, b)
}
func (m *GetTokenFromCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenFromCodeResponse.Marshal(b, m, deterministic)
}
func (dst *GetTokenFromCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenFromCodeResponse.Merge(dst, src)
}
func (m *GetTokenFromCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenFromCodeResponse.Size(m)
}
func (m *GetTokenFromCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenFromCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenFromCodeResponse proto.InternalMessageInfo

func (m *GetTokenFromCodeResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetTokenFromCodeResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserInfoRequest)(nil), "user.GetUserInfoRequest")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "user.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "user.DeleteUserResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "user.GetTokenRequest")
	proto.RegisterType((*GetAccessTokenResponse)(nil), "user.GetAccessTokenResponse")
	proto.RegisterType((*GetUserByAccessTokenRequest)(nil), "user.GetUserByAccessTokenRequest")
	proto.RegisterType((*GetUserByAccessTokenResponse)(nil), "user.GetUserByAccessTokenResponse")
	proto.RegisterType((*GetRefreshTokenResponse)(nil), "user.GetRefreshTokenResponse")
	proto.RegisterType((*RefreshAccessTokenRequest)(nil), "user.RefreshAccessTokenRequest")
	proto.RegisterType((*RefreshAccessTokenResponse)(nil), "user.RefreshAccessTokenResponse")
	proto.RegisterType((*CreateAppRequest)(nil), "user.CreateAppRequest")
	proto.RegisterType((*CreateAppResponse)(nil), "user.CreateAppResponse")
	proto.RegisterType((*GetAppInfoRequest)(nil), "user.GetAppInfoRequest")
	proto.RegisterType((*GetAppInfoResponse)(nil), "user.GetAppInfoResponse")
	proto.RegisterType((*GetOAuthCodeRequest)(nil), "user.GetOAuthCodeRequest")
	proto.RegisterType((*GetOAuthCodeResponse)(nil), "user.GetOAuthCodeResponse")
	proto.RegisterType((*GetTokenFromCodeRequest)(nil), "user.GetTokenFromCodeRequest")
	proto.RegisterType((*GetTokenFromCodeResponse)(nil), "user.GetTokenFromCodeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GetAccessToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error)
	GetRefreshToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetRefreshTokenResponse, error)
	RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*RefreshAccessTokenResponse, error)
	GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...grpc.CallOption) (*GetUserByAccessTokenResponse, error)
	CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error)
	GetAppInfo(ctx context.Context, in *GetAppInfoRequest, opts ...grpc.CallOption) (*GetAppInfoResponse, error)
	GetOAuthCode(ctx context.Context, in *GetOAuthCodeRequest, opts ...grpc.CallOption) (*GetOAuthCodeResponse, error)
	GetTokenFromCode(ctx context.Context, in *GetTokenFromCodeRequest, opts ...grpc.CallOption) (*GetTokenFromCodeResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.user/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.user/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/user.user/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/user.user/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAccessToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetAccessTokenResponse, error) {
	out := new(GetAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetRefreshToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetRefreshTokenResponse, error) {
	out := new(GetRefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetRefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) RefreshAccessToken(ctx context.Context, in *RefreshAccessTokenRequest, opts ...grpc.CallOption) (*RefreshAccessTokenResponse, error) {
	out := new(RefreshAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/RefreshAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserByAccessToken(ctx context.Context, in *GetUserByAccessTokenRequest, opts ...grpc.CallOption) (*GetUserByAccessTokenResponse, error) {
	out := new(GetUserByAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetUserByAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error) {
	out := new(CreateAppResponse)
	err := c.cc.Invoke(ctx, "/user.user/CreateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAppInfo(ctx context.Context, in *GetAppInfoRequest, opts ...grpc.CallOption) (*GetAppInfoResponse, error) {
	out := new(GetAppInfoResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetAppInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetOAuthCode(ctx context.Context, in *GetOAuthCodeRequest, opts ...grpc.CallOption) (*GetOAuthCodeResponse, error) {
	out := new(GetOAuthCodeResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetOAuthCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetTokenFromCode(ctx context.Context, in *GetTokenFromCodeRequest, opts ...grpc.CallOption) (*GetTokenFromCodeResponse, error) {
	out := new(GetTokenFromCodeResponse)
	err := c.cc.Invoke(ctx, "/user.user/GetTokenFromCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	GetUserInfo(context.Context, *GetUserInfoRequest) (*UserInfo, error)
	CreateUser(context.Context, *CreateUserRequest) (*UserInfo, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetAccessToken(context.Context, *GetTokenRequest) (*GetAccessTokenResponse, error)
	GetRefreshToken(context.Context, *GetTokenRequest) (*GetRefreshTokenResponse, error)
	RefreshAccessToken(context.Context, *RefreshAccessTokenRequest) (*RefreshAccessTokenResponse, error)
	GetUserByAccessToken(context.Context, *GetUserByAccessTokenRequest) (*GetUserByAccessTokenResponse, error)
	CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error)
	GetAppInfo(context.Context, *GetAppInfoRequest) (*GetAppInfoResponse, error)
	GetOAuthCode(context.Context, *GetOAuthCodeRequest) (*GetOAuthCodeResponse, error)
	GetTokenFromCode(context.Context, *GetTokenFromCodeRequest) (*GetTokenFromCodeResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAccessToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetRefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetRefreshToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_RefreshAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).RefreshAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/RefreshAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).RefreshAccessToken(ctx, req.(*RefreshAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserByAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserByAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetUserByAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserByAccessToken(ctx, req.(*GetUserByAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateApp(ctx, req.(*CreateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAppInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAppInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetAppInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAppInfo(ctx, req.(*GetAppInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetOAuthCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOAuthCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetOAuthCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetOAuthCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetOAuthCode(ctx, req.(*GetOAuthCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetTokenFromCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenFromCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetTokenFromCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/GetTokenFromCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetTokenFromCode(ctx, req.(*GetTokenFromCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _User_DeleteUser_Handler,
		},
		{
			MethodName: "GetAccessToken",
			Handler:    _User_GetAccessToken_Handler,
		},
		{
			MethodName: "GetRefreshToken",
			Handler:    _User_GetRefreshToken_Handler,
		},
		{
			MethodName: "RefreshAccessToken",
			Handler:    _User_RefreshAccessToken_Handler,
		},
		{
			MethodName: "GetUserByAccessToken",
			Handler:    _User_GetUserByAccessToken_Handler,
		},
		{
			MethodName: "CreateApp",
			Handler:    _User_CreateApp_Handler,
		},
		{
			MethodName: "GetAppInfo",
			Handler:    _User_GetAppInfo_Handler,
		},
		{
			MethodName: "GetOAuthCode",
			Handler:    _User_GetOAuthCode_Handler,
		},
		{
			MethodName: "GetTokenFromCode",
			Handler:    _User_GetTokenFromCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/user/proto/user.proto",
}

func init() { proto.RegisterFile("pkg/user/proto/user.proto", fileDescriptor_user_d91e02009efc5113) }

var fileDescriptor_user_d91e02009efc5113 = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0xb3, 0x51, 0xda, 0xdb, 0x34, 0x56, 0x33, 0xba, 0xcc, 0x74, 0x50, 0x8c, 0x84, 0x26,
	0x1e, 0x36, 0x04, 0x42, 0x3c, 0x6c, 0x62, 0x94, 0x01, 0xd5, 0x9e, 0x10, 0x85, 0x89, 0x27, 0x04,
	0x59, 0x73, 0x63, 0xd5, 0x58, 0x62, 0xe2, 0x54, 0x13, 0x7f, 0x2a, 0xff, 0x0d, 0x8a, 0x63, 0x3b,
	0x4e, 0x9c, 0x4c, 0x15, 0xf0, 0x96, 0xfb, 0xf5, 0x7d, 0x67, 0x9f, 0xef, 0x53, 0x60, 0x8b, 0x5f,
	0x7c, 0xdf, 0x9b, 0x0b, 0x4c, 0xf6, 0x78, 0x12, 0xa7, 0xb1, 0xfc, 0xdc, 0x95, 0x9f, 0x64, 0x39,
	0xfb, 0x66, 0x8f, 0x80, 0x8c, 0x31, 0x3d, 0x11, 0x98, 0x1c, 0x47, 0x67, 0xf1, 0x04, 0x7f, 0xce,
	0x51, 0xa4, 0x64, 0x1d, 0x96, 0xe6, 0xb3, 0xd0, 0x6f, 0x0d, 0x5b, 0x3b, 0xdd, 0x49, 0xf6, 0xc9,
	0x26, 0xd0, 0xd1, 0x49, 0x6e, 0x94, 0x50, 0xe8, 0x64, 0x68, 0x51, 0x70, 0x89, 0xbe, 0x27, 0xdd,
	0xc6, 0x26, 0x3e, 0xdc, 0x9c, 0x89, 0x51, 0x78, 0x39, 0x8b, 0xfc, 0xa5, 0x61, 0x6b, 0xa7, 0x33,
	0xd1, 0x26, 0x0b, 0xa0, 0x77, 0x94, 0x60, 0x90, 0x62, 0x86, 0xac, 0xa9, 0x37, 0xe0, 0x46, 0x1a,
	0x5f, 0x60, 0xa4, 0xe0, 0x73, 0xe3, 0x5a, 0x02, 0x0a, 0x1d, 0x1e, 0x08, 0x71, 0x15, 0x27, 0xa1,
	0x64, 0xe8, 0x4e, 0x8c, 0xcd, 0xbe, 0x42, 0xef, 0x84, 0x87, 0x15, 0x8a, 0x01, 0x74, 0xb3, 0xe2,
	0x4f, 0x16, 0x4d, 0xe1, 0xd0, 0xa7, 0xf3, 0x4a, 0xa7, 0x6b, 0x24, 0xd8, 0x00, 0x62, 0x13, 0x08,
	0x1e, 0x47, 0x02, 0xd9, 0x11, 0xf4, 0xde, 0xe0, 0x0f, 0xfc, 0x27, 0xda, 0x0c, 0xda, 0x06, 0x51,
	0xd0, 0xc7, 0x70, 0x6b, 0x8c, 0xa9, 0xac, 0xd1, 0xc0, 0xf6, 0xe5, 0xb4, 0xae, 0xb9, 0x1c, 0xaf,
	0xd2, 0xfb, 0x2b, 0xe8, 0x8f, 0x31, 0x1d, 0x4d, 0xa7, 0x28, 0x84, 0x02, 0xcc, 0x49, 0x1a, 0x86,
	0xe0, 0xb6, 0xb8, 0x0f, 0x77, 0xd5, 0xeb, 0x79, 0xfd, 0xab, 0x84, 0xb3, 0xc0, 0x89, 0xd9, 0x13,
	0x18, 0xd4, 0x17, 0xab, 0x26, 0xdc, 0x47, 0xb8, 0x07, 0x9b, 0x63, 0x4c, 0x27, 0x78, 0x96, 0xa0,
	0x38, 0x5f, 0xa0, 0x63, 0x76, 0x08, 0x5b, 0x2a, 0xbb, 0xa6, 0x3b, 0x06, 0xab, 0x89, 0x05, 0xa5,
	0x2a, 0x4b, 0x3e, 0x76, 0x0a, 0xb4, 0x0e, 0x40, 0x91, 0x0e, 0x61, 0x25, 0x28, 0xdc, 0x0a, 0xc0,
	0x76, 0x39, 0x1c, 0x5e, 0x0d, 0xc7, 0x01, 0xac, 0xe7, 0x6b, 0x30, 0xe2, 0xdc, 0xda, 0x82, 0xf8,
	0x2a, 0xc2, 0x44, 0x1f, 0x47, 0x1a, 0x84, 0xc0, 0xb2, 0xb5, 0x01, 0xf2, 0x9b, 0xed, 0xeb, 0x25,
	0x92, 0xd5, 0xaa, 0xb1, 0x35, 0xf0, 0xcc, 0xcd, 0x79, 0xb3, 0x90, 0xf4, 0xa1, 0x2d, 0x70, 0x9a,
	0x60, 0xaa, 0x4a, 0x95, 0xc5, 0x1e, 0x42, 0x2f, 0x7b, 0x01, 0x9c, 0xdb, 0xcb, 0x5f, 0x29, 0x66,
	0x2f, 0xa5, 0x44, 0x98, 0xa4, 0xe2, 0xc2, 0x17, 0xec, 0x10, 0xe1, 0xf6, 0x18, 0xd3, 0xf7, 0xa3,
	0x79, 0x7a, 0x7e, 0x14, 0x87, 0xa8, 0x69, 0xfa, 0xd0, 0x0e, 0x38, 0x3f, 0x31, 0x54, 0xca, 0xfa,
	0xeb, 0x55, 0x7f, 0x0c, 0x1b, 0x65, 0x1a, 0xd5, 0x28, 0x81, 0xe5, 0x69, 0x1c, 0xea, 0xcd, 0x90,
	0xdf, 0x6c, 0x2a, 0x1f, 0x92, 0xbc, 0xfe, 0x77, 0x49, 0x7c, 0x69, 0xb7, 0x55, 0x93, 0x6e, 0xb5,
	0xea, 0x95, 0x5a, 0x1d, 0x40, 0x37, 0xe0, 0xfc, 0x63, 0x7e, 0xb3, 0x79, 0x3f, 0x85, 0x83, 0x7d,
	0x03, 0xdf, 0x25, 0xf9, 0x9f, 0x2f, 0xe7, 0xe9, 0xef, 0x36, 0x48, 0x15, 0x27, 0x2f, 0x60, 0xc5,
	0x52, 0x71, 0xe2, 0xef, 0x4a, 0x9d, 0x77, 0x85, 0x9d, 0xae, 0xe5, 0x11, 0x93, 0xf9, 0x1c, 0xa0,
	0x90, 0x60, 0xb2, 0x99, 0x47, 0x1d, 0x51, 0x76, 0xca, 0x0e, 0x01, 0x0a, 0xd5, 0xd3, 0x65, 0x8e,
	0xd0, 0x52, 0xdf, 0x0d, 0xa8, 0xf3, 0x1f, 0x02, 0x14, 0xda, 0xa6, 0x01, 0x1c, 0xc9, 0xd4, 0x00,
	0xae, 0x0c, 0x92, 0xb7, 0xb0, 0x56, 0xd6, 0x2e, 0x72, 0xc7, 0x1c, 0xda, 0xde, 0x72, 0x3a, 0x30,
	0xee, 0xba, 0x0d, 0x1e, 0x4b, 0x35, 0xb5, 0x15, 0xa5, 0x09, 0x67, 0xdb, 0xb8, 0x6b, 0xf5, 0xe7,
	0x33, 0x10, 0x57, 0x28, 0xc8, 0xfd, 0xbc, 0xa8, 0x51, 0x83, 0xe8, 0xb0, 0x39, 0x41, 0x01, 0x7f,
	0x91, 0xcf, 0xda, 0x51, 0x49, 0xf2, 0xa0, 0x34, 0xe3, 0x3a, 0xf9, 0xa5, 0xec, 0xba, 0x14, 0x05,
	0x7f, 0x00, 0x5d, 0x23, 0x1f, 0xa4, 0x6f, 0xcf, 0xbf, 0x50, 0x23, 0xba, 0xe9, 0xf8, 0x8b, 0x31,
	0x16, 0xd2, 0xa0, 0xc7, 0xe8, 0x28, 0x0a, 0xf5, 0xdd, 0x80, 0x19, 0xe3, 0xaa, 0xbd, 0xb4, 0x64,
	0xcb, 0x64, 0x56, 0xf5, 0x82, 0xd2, 0xba, 0x90, 0x82, 0xf9, 0x00, 0xeb, 0xd5, 0x55, 0x23, 0xdb,
	0xe5, 0x39, 0x56, 0xf6, 0x9c, 0xde, 0x6b, 0x0a, 0xe7, 0x90, 0xa7, 0x6d, 0xf9, 0x97, 0xf4, 0xec,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xb3, 0xde, 0x42, 0x42, 0x09, 0x00, 0x00,
}
